version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env