version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb+srv://dst-airline-MRFF:gVlxqqz76838njKp@cluster0.vauxcgo.mongodb.net/test?retryWrites=true&w=majority

  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    environment:
      MONGO_URI: mongodb+srv://dst-airline-MRFF:gVlxqqz76838njKp@cluster0.vauxcgo.mongodb.net/test?retryWrites=true&w=majority
      API_KEY: '4f2f845653e64a21b22163313242808'
